=begin
#OpenAPI UniBee

#UniBee Api Server

The version of the OpenAPI document: daily,buildtime:202602241319

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Unibee::CheckoutSetupApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CheckoutSetupApi' do
  before do
    # run before each test
    @api_instance = Unibee::CheckoutSetupApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CheckoutSetupApi' do
    it 'should create an instance of CheckoutSetupApi' do
      expect(@api_instance).to be_instance_of(Unibee::CheckoutSetupApi)
    end
  end

  # unit tests for merchant_checkout_archive_post
  # Archive Merchant Checkout
  # @param unibee_api_merchant_checkout_archive_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoClearTotpPost200Response]
  describe 'merchant_checkout_archive_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_checkout_detail_get
  # Get Merchant Checkout Detail
  # @param checkout_id checkout id
  # @param [Hash] opts the optional parameters
  # @return [MerchantCheckoutDetailGet200Response]
  describe 'merchant_checkout_detail_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_checkout_detail_post
  # Get Merchant Checkout Detail
  # @param unibee_api_merchant_checkout_detail_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantCheckoutDetailGet200Response]
  describe 'merchant_checkout_detail_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_checkout_edit_checkout_post
  # Edit Merchant Checkout
  # @param unibee_api_merchant_checkout_edit_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantCheckoutDetailGet200Response]
  describe 'merchant_checkout_edit_checkout_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_checkout_get_link_get
  # Get Merchant Checkout Link
  # @param checkout_id checkout id
  # @param plan_id 
  # @param [Hash] opts the optional parameters
  # @return [MerchantCheckoutGetLinkGet200Response]
  describe 'merchant_checkout_get_link_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_checkout_get_link_post
  # Get Merchant Checkout Link
  # @param unibee_api_merchant_checkout_get_link_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantCheckoutGetLinkGet200Response]
  describe 'merchant_checkout_get_link_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_checkout_list_get
  # Get Merchant Checkout list
  # @param [Hash] opts the optional parameters
  # @option opts [String] :search_key Search checkout id|name|description
  # @return [MerchantCheckoutListGet200Response]
  describe 'merchant_checkout_list_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_checkout_list_post
  # Get Merchant Checkout list
  # @param unibee_api_merchant_checkout_list_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantCheckoutListGet200Response]
  describe 'merchant_checkout_list_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_checkout_new_checkout_post
  # New Merchant Checkout
  # @param unibee_api_merchant_checkout_new_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantCheckoutDetailGet200Response]
  describe 'merchant_checkout_new_checkout_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
