=begin
#OpenAPI UniBee

#UniBee Api Server

The version of the OpenAPI document: daily,buildtime:202602241319

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Unibee::MemberAuthenticationApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MemberAuthenticationApi' do
  before do
    # run before each test
    @api_instance = Unibee::MemberAuthenticationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MemberAuthenticationApi' do
    it 'should create an instance of MemberAuthenticationApi' do
      expect(@api_instance).to be_instance_of(Unibee::MemberAuthenticationApi)
    end
  end

  # unit tests for merchant_auth_session_login_post
  # Session Login
  # Session login
  # @param unibee_api_merchant_auth_session_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSessionLoginPost200Response]
  describe 'merchant_auth_session_login_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_auth_sso_clear_totp_post
  # Admin Member Clear Member 2FA Key With ResumeCode
  # @param unibee_api_merchant_auth_clear_totp_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoClearTotpPost200Response]
  describe 'merchant_auth_sso_clear_totp_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_auth_sso_login_otp_post
  # OTP Login
  # Send email to member with OTP code
  # @param unibee_api_merchant_auth_login_otp_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoClearTotpPost200Response]
  describe 'merchant_auth_sso_login_otp_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_auth_sso_login_otp_verify_post
  # OTP Login Code Verification
  # OTP login for member, verify OTP code
  # @param unibee_api_merchant_auth_login_otp_verify_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoLoginPost200Response]
  describe 'merchant_auth_sso_login_otp_verify_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_auth_sso_login_post
  # Merchant Password Login
  # Merchant Password login
  # @param unibee_api_merchant_auth_login_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoLoginPost200Response]
  describe 'merchant_auth_sso_login_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_auth_sso_oauth_github_get
  # Get Oauth Github
  # Merchant Oauth Github
  # @param [Hash] opts the optional parameters
  # @option opts [String] :github_code Github Code
  # @return [MerchantAuthSsoOauthGithubGet200Response]
  describe 'merchant_auth_sso_oauth_github_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_auth_sso_oauth_google_get
  # Get Oauth Google
  # Merchant Oauth Google
  # @param [Hash] opts the optional parameters
  # @option opts [String] :google_code Google Code
  # @option opts [String] :redirect_uri The Google Redirect Uri
  # @return [MerchantAuthSsoOauthGoogleGet200Response]
  describe 'merchant_auth_sso_oauth_google_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_auth_sso_oauth_login_post
  # OAuth Login
  # OAuth login. Pass OAuth token in request header (Auth.js JWT). Headers: X-Auth-JS-Token | X-Auth-Token | X-OAuth-Token
  # @param unibee_api_merchant_auth_login_o_auth_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoLoginPost200Response]
  describe 'merchant_auth_sso_oauth_login_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_auth_sso_oauth_members_get
  # Get Oauth Members
  # Merchant Get Oauth Connected Members. Pass OAuth token in request header (Auth.js JWT). Headers: X-Auth-JS-Token | X-Auth-Token | X-OAuth-Token
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoOauthMembersGet200Response]
  describe 'merchant_auth_sso_oauth_members_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_auth_sso_oauth_register_post
  # Register OAuth
  # Merchant OAuth Register. Pass OAuth token in request header (Auth.js JWT). Headers: X-Auth-JS-Token | X-Auth-Token | X-OAuth-Token
  # @param unibee_api_merchant_auth_register_o_auth_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoLoginPost200Response]
  describe 'merchant_auth_sso_oauth_register_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_auth_sso_oauth_setup_post
  # OAuth Setup
  # Member OAuth Setup. Pass OAuth token in request header (Auth.js JWT). Headers: X-Auth-JS-Token | X-Auth-Token | X-OAuth-Token
  # @param unibee_api_merchant_auth_setup_o_auth_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoLoginPost200Response]
  describe 'merchant_auth_sso_oauth_setup_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_auth_sso_password_forget_otp_post
  # OTP Password Forget
  # Send email to member with OTP code
  # @param unibee_api_merchant_auth_password_forget_otp_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoClearTotpPost200Response]
  describe 'merchant_auth_sso_password_forget_otp_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_auth_sso_password_forget_otp_verify_post
  # OTP Password Forget Code Verification
  # Password forget OTP process, verify OTP code
  # @param unibee_api_merchant_auth_password_forget_otp_verify_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoClearTotpPost200Response]
  describe 'merchant_auth_sso_password_forget_otp_verify_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_auth_sso_password_forget_totp_verify_post
  # 2FA Password Forget Code Verification
  # Password forget 2FA process, verify 2FA code
  # @param unibee_api_merchant_auth_password_forget_totp_verify_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoClearTotpPost200Response]
  describe 'merchant_auth_sso_password_forget_totp_verify_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_auth_sso_password_setup_post
  # Password Setup
  # Member Password Setup
  # @param unibee_api_merchant_auth_password_setup_otp_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoLoginPost200Response]
  describe 'merchant_auth_sso_password_setup_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_auth_sso_register_email_check_post
  # Register Email Check
  # Check Register Email
  # @param unibee_api_merchant_auth_register_email_check_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoRegisterEmailCheckPost200Response]
  describe 'merchant_auth_sso_register_email_check_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_auth_sso_register_post
  # Register
  # Register with owner permission, send email with OTP code
  # @param unibee_api_merchant_auth_register_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoClearTotpPost200Response]
  describe 'merchant_auth_sso_register_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_auth_sso_register_verify_post
  # Register Verify
  # Merchant Register, verify OTP code 
  # @param unibee_api_merchant_auth_register_verify_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoLoginPost200Response]
  describe 'merchant_auth_sso_register_verify_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_auth_sso_register_without_verification_post
  # RegisterWithoutCode
  # Register with owner permission without code verification
  # @param unibee_api_merchant_auth_register_without_verification_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoLoginPost200Response]
  describe 'merchant_auth_sso_register_without_verification_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
