=begin
#OpenAPI UniBee

#UniBee Api Server

The version of the OpenAPI document: daily,buildtime:202602241319

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Unibee::ProductApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ProductApi' do
  before do
    # run before each test
    @api_instance = Unibee::ProductApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProductApi' do
    it 'should create an instance of ProductApi' do
      expect(@api_instance).to be_instance_of(Unibee::ProductApi)
    end
  end

  # unit tests for merchant_product_activate_post
  # Activate Product
  # @param unibee_api_merchant_product_activate_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoClearTotpPost200Response]
  describe 'merchant_product_activate_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_product_copy_post
  # Copy Product
  # @param unibee_api_merchant_product_copy_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantProductCopyPost200Response]
  describe 'merchant_product_copy_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_product_delete_post
  # Delete Product
  # Product can being deleted when has no plan linked
  # @param unibee_api_merchant_product_delete_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoClearTotpPost200Response]
  describe 'merchant_product_delete_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_product_detail_get
  # Product Detail
  # @param product_id ProductId
  # @param [Hash] opts the optional parameters
  # @return [MerchantProductCopyPost200Response]
  describe 'merchant_product_detail_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_product_detail_post
  # Product Detail
  # @param unibee_api_merchant_product_detail_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantProductCopyPost200Response]
  describe 'merchant_product_detail_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_product_edit_post
  # Edit Product
  # Edit exist product, product is editable for both active and inactive status 
  # @param unibee_api_merchant_product_edit_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantProductCopyPost200Response]
  describe 'merchant_product_edit_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_product_inactivate_post
  # Inactivate Product
  # @param unibee_api_merchant_product_inactive_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoClearTotpPost200Response]
  describe 'merchant_product_inactivate_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_product_list_get
  # Get Product List
  # @param [Hash] opts the optional parameters
  # @option opts [Array<Integer>] :status Filter, Default All，,Status，1-active，2-inactive
  # @option opts [String] :sort_field Sort Field，id|create_time|gmt_modify，Default id
  # @option opts [String] :sort_type Sort Type，asc|desc，Default desc
  # @option opts [Integer] :page Page, Start 0
  # @option opts [Integer] :count Count Of Per Page
  # @return [MerchantProductListGet200Response]
  describe 'merchant_product_list_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_product_list_post
  # Get Product List
  # @param unibee_api_merchant_product_list_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantProductListGet200Response]
  describe 'merchant_product_list_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_product_new_post
  # Create Product
  # @param unibee_api_merchant_product_new_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantProductCopyPost200Response]
  describe 'merchant_product_new_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
