=begin
#OpenAPI UniBee

#UniBee Api Server

The version of the OpenAPI document: daily,buildtime:202602241319

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Unibee::SubscriptionImportApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SubscriptionImportApi' do
  before do
    # run before each test
    @api_instance = Unibee::SubscriptionImportApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SubscriptionImportApi' do
    it 'should create an instance of SubscriptionImportApi' do
      expect(@api_instance).to be_instance_of(Unibee::SubscriptionImportApi)
    end
  end

  # unit tests for merchant_subscription_active_subscription_import_post
  # Active Subscription Import(allows repetition imports)
  # Each repetition import overrides existing subscriptions with matching ExternalSubscriptionId.
  # @param unibee_api_merchant_subscription_active_subscription_import_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantSubscriptionActiveSubscriptionImportPost200Response]
  describe 'merchant_subscription_active_subscription_import_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_subscription_history_subscription_import_post
  # History Subscription Import(Allows repetition imports)
  # Each repetition import overrides existing subscriptions with matching ExternalSubscriptionId.
  # @param unibee_api_merchant_subscription_history_subscription_import_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantSubscriptionActiveSubscriptionImportPost200Response]
  describe 'merchant_subscription_history_subscription_import_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
