=begin
#OpenAPI UniBee

#UniBee Api Server

The version of the OpenAPI document: daily,buildtime:202602241319

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Unibee::SubscriptionTimelineApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SubscriptionTimelineApi' do
  before do
    # run before each test
    @api_instance = Unibee::SubscriptionTimelineApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SubscriptionTimelineApi' do
    it 'should create an instance of SubscriptionTimelineApi' do
      expect(@api_instance).to be_instance_of(Unibee::SubscriptionTimelineApi)
    end
  end

  # unit tests for merchant_subscription_timeline_list_get
  # Get Subscription TimeLine List
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :user_id Filter UserId, Default All 
  # @option opts [String] :sort_field Sort Field，gmt_create|gmt_modify，Default gmt_modify
  # @option opts [String] :sort_type Sort Type，asc|desc，Default desc
  # @option opts [Integer] :page Page, Start With 0
  # @option opts [Integer] :count Count Of Page
  # @return [MerchantSubscriptionTimelineListGet200Response]
  describe 'merchant_subscription_timeline_list_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_subscription_timeline_list_post
  # Get Subscription TimeLine List
  # @param unibee_api_merchant_subscription_time_line_list_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantSubscriptionTimelineListGet200Response]
  describe 'merchant_subscription_timeline_list_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
