=begin
#OpenAPI UniBee

#UniBee Api Server

The version of the OpenAPI document: daily,buildtime:202602241319

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Unibee::UserApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UserApi' do
  before do
    # run before each test
    @api_instance = Unibee::UserApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserApi' do
    it 'should create an instance of UserApi' do
      expect(@api_instance).to be_instance_of(Unibee::UserApi)
    end
  end

  # unit tests for merchant_user_admin_note_list_get
  # Get User Admin Note List
  # @param user_id The id of user, either ExternalUserId or UserId needed
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page, Start With 0
  # @option opts [Integer] :count Count Of Page
  # @return [MerchantUserAdminNoteListGet200Response]
  describe 'merchant_user_admin_note_list_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_user_admin_note_list_post
  # Get User Admin Note List
  # @param unibee_api_merchant_user_admin_note_list_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantUserAdminNoteListGet200Response]
  describe 'merchant_user_admin_note_list_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_user_change_email_post
  # Change User Email
  # @param unibee_api_merchant_user_change_email_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoClearTotpPost200Response]
  describe 'merchant_user_change_email_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_user_change_gateway_post
  # Change User Default Gateway
  # @param unibee_api_merchant_user_change_gateway_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoClearTotpPost200Response]
  describe 'merchant_user_change_gateway_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_user_clear_auto_charge_method_post
  # Clear AutoCharge Method
  # @param unibee_api_merchant_user_clear_auto_charge_method_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoClearTotpPost200Response]
  describe 'merchant_user_clear_auto_charge_method_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_user_count_get
  # User Count
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :create_time_start CreateTimeStart，UTC timestamp，seconds
  # @option opts [Integer] :create_time_end CreateTimeEnd，UTC timestamp，seconds
  # @return [MerchantUserCountGet200Response]
  describe 'merchant_user_count_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_user_delete_post
  # Delete User
  # @param unibee_api_merchant_user_delete_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoClearTotpPost200Response]
  describe 'merchant_user_delete_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_user_get_get
  # Get User Profile
  # @param user_id UserId
  # @param [Hash] opts the optional parameters
  # @return [MerchantUserGetGet200Response]
  describe 'merchant_user_get_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_user_list_get
  # User List
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :user_id Filter UserId
  # @option opts [String] :external_user_id ExternalUserId
  # @option opts [String] :first_name Search FirstName
  # @option opts [String] :last_name Search LastName
  # @option opts [String] :email Search Filter Email
  # @option opts [String] :search_key Search FirstName|LastName|Email|Phone|Address|ExternalUserId
  # @option opts [Array<Integer>] :plan_ids PlanIds, Search Filter PlanIds
  # @option opts [Array<Integer>] :gateway_ids GatewayIds, Search Filter GatewayIds
  # @option opts [String] :subscription_id Search Filter SubscriptionId
  # @option opts [Array<Integer>] :sub_status Filter, Default All，1-Pending｜2-Active｜3-Suspend | 4-Cancel | 5-Expire | 6- Suspend| 7-Incomplete | 8-Processing | 9-Failed
  # @option opts [Array<Integer>] :status Status, 0-Active｜2-Frozen
  # @option opts [Boolean] :delete_include Deleted Involved，Need Admin
  # @option opts [String] :sort_field Sort，user_id|gmt_create|email|user_name|subscription_name|subscription_status|payment_method|recurring_amount|billing_type，Default gmt_create
  # @option opts [String] :sort_type Sort Type，asc|desc，Default desc
  # @option opts [Integer] :page Page,Start 0
  # @option opts [Integer] :count Count OF Page
  # @option opts [Integer] :create_time_start CreateTimeStart，UTC timestamp，seconds
  # @option opts [Integer] :create_time_end CreateTimeEnd，UTC timestamp，seconds
  # @return [MerchantUserListGet200Response]
  describe 'merchant_user_list_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_user_list_post
  # User List
  # @param unibee_api_merchant_user_list_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantUserListGet200Response]
  describe 'merchant_user_list_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_user_new_admin_note_post
  # New Admin Note
  # @param unibee_api_merchant_user_new_admin_note_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoClearTotpPost200Response]
  describe 'merchant_user_new_admin_note_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_user_new_post
  # New User
  # User Creation If Not Exist 
  # @param unibee_api_merchant_user_new_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantUserNewPost200Response]
  describe 'merchant_user_new_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_user_resume_user_post
  # Resume User
  # @param unibee_api_merchant_user_release_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoClearTotpPost200Response]
  describe 'merchant_user_resume_user_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_user_search_get
  # User Search
  # @param [Hash] opts the optional parameters
  # @option opts [String] :search_key SearchKey, Will Search UserId|Email|UserName|CompanyName|SubscriptionId|VatNumber|InvoiceId||PaymentId
  # @return [MerchantUserSearchGet200Response]
  describe 'merchant_user_search_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_user_search_post
  # User Search
  # @param unibee_api_merchant_user_search_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantUserSearchGet200Response]
  describe 'merchant_user_search_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_user_suspend_user_post
  # Suspend User
  # @param unibee_api_merchant_user_frozen_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantAuthSsoClearTotpPost200Response]
  describe 'merchant_user_suspend_user_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_user_update_post
  # Update User Profile
  # @param unibee_api_merchant_user_update_req 
  # @param [Hash] opts the optional parameters
  # @return [MerchantUserGetGet200Response]
  describe 'merchant_user_update_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
