=begin
#OpenAPI UniBee

#UniBee Api Server

The version of the OpenAPI document: daily,buildtime:202602241319

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Unibee::MerchantMetricDeletePost200ResponseData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Unibee::MerchantMetricDeletePost200ResponseData do
  let(:instance) { Unibee::MerchantMetricDeletePost200ResponseData.new }

  describe 'test an instance of MerchantMetricDeletePost200ResponseData' do
    it 'should create an instance of MerchantMetricDeletePost200ResponseData' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Unibee::MerchantMetricDeletePost200ResponseData)
    end
  end

  describe 'test attribute "merchant_metric"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
