=begin
#OpenAPI UniBee

#UniBee Api Server

The version of the OpenAPI document: daily,buildtime:202602241319

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Unibee::MerchantPaymentListGet200ResponseData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Unibee::MerchantPaymentListGet200ResponseData do
  let(:instance) { Unibee::MerchantPaymentListGet200ResponseData.new }

  describe 'test an instance of MerchantPaymentListGet200ResponseData' do
    it 'should create an instance of MerchantPaymentListGet200ResponseData' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Unibee::MerchantPaymentListGet200ResponseData)
    end
  end

  describe 'test attribute "payment_details"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "total"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
