=begin
#OpenAPI UniBee

#UniBee Api Server

The version of the OpenAPI document: daily,buildtime:202602241319

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Unibee::UnibeeApiMerchantMetricNewReq
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Unibee::UnibeeApiMerchantMetricNewReq do
  let(:instance) { Unibee::UnibeeApiMerchantMetricNewReq.new }

  describe 'test an instance of UnibeeApiMerchantMetricNewReq' do
    it 'should create an instance of UnibeeApiMerchantMetricNewReq' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Unibee::UnibeeApiMerchantMetricNewReq)
    end
  end

  describe 'test attribute "aggregation_property"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "aggregation_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "meta_data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "metric_description"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "metric_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "unit"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
