=begin
#OpenAPI UniBee

#UniBee Api Server

The version of the OpenAPI document: daily,buildtime:202602241319

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Unibee::UnibeeApiBeanUserMetricChargeInvoiceItemEntity
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Unibee::UnibeeApiBeanUserMetricChargeInvoiceItemEntity do
  let(:instance) { Unibee::UnibeeApiBeanUserMetricChargeInvoiceItemEntity.new }

  describe 'test an instance of UnibeeApiBeanUserMetricChargeInvoiceItemEntity' do
    it 'should create an instance of UnibeeApiBeanUserMetricChargeInvoiceItemEntity' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Unibee::UnibeeApiBeanUserMetricChargeInvoiceItemEntity)
    end
  end

  describe 'test attribute "metered_charge_stats"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "recurring_charge_stats"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
