=begin
#OpenAPI UniBee

#UniBee Api Server

The version of the OpenAPI document: daily,buildtime:202602241319

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Unibee::UnibeeApiMerchantInvoicePdfGenerateReq
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Unibee::UnibeeApiMerchantInvoicePdfGenerateReq do
  let(:instance) { Unibee::UnibeeApiMerchantInvoicePdfGenerateReq.new }

  describe 'test an instance of UnibeeApiMerchantInvoicePdfGenerateReq' do
    it 'should create an instance of UnibeeApiMerchantInvoicePdfGenerateReq' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Unibee::UnibeeApiMerchantInvoicePdfGenerateReq)
    end
  end

  describe 'test attribute "invoice_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "send_user_email"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
