=begin
#OpenAPI UniBee

#UniBee Api Server

The version of the OpenAPI document: daily,buildtime:202602241319

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Unibee::UnibeeApiMerchantInvoiceRefundReq
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Unibee::UnibeeApiMerchantInvoiceRefundReq do
  let(:instance) { Unibee::UnibeeApiMerchantInvoiceRefundReq.new }

  describe 'test an instance of UnibeeApiMerchantInvoiceRefundReq' do
    it 'should create an instance of UnibeeApiMerchantInvoiceRefundReq' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Unibee::UnibeeApiMerchantInvoiceRefundReq)
    end
  end

  describe 'test attribute "invoice_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "payment_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "reason"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "refund_amount"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "refund_no"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
