=begin
#OpenAPI UniBee

#UniBee Api Server

The version of the OpenAPI document: daily,buildtime:202602241319

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Unibee::UnibeeApiMerchantEmailDeleteLocalizationVersionReq
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Unibee::UnibeeApiMerchantEmailDeleteLocalizationVersionReq do
  let(:instance) { Unibee::UnibeeApiMerchantEmailDeleteLocalizationVersionReq.new }

  describe 'test an instance of UnibeeApiMerchantEmailDeleteLocalizationVersionReq' do
    it 'should create an instance of UnibeeApiMerchantEmailDeleteLocalizationVersionReq' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Unibee::UnibeeApiMerchantEmailDeleteLocalizationVersionReq)
    end
  end

  describe 'test attribute "template_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "version_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
