=begin
#OpenAPI UniBee

#UniBee Api Server

The version of the OpenAPI document: daily,buildtime:202602241319

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'date'
require 'time'

module Unibee
  class UnibeeApiSystemSubscriptionSubscriptionEndpointBlacklistStatus
    # Current punishment level: 0=No restriction, 1=Temporary rate limit (5min), 2=Short-term blacklist (1h), 3=Long-term blacklist (24h)
    attr_accessor :current_level

    # Endpoint name (Preview or Create)
    attr_accessor :endpoint

    # Description of current level
    attr_accessor :level_description

    # Warning about what happens if violated again
    attr_accessor :next_level_warning

    # Unix timestamp when current punishment expires (0 if no punishment)
    attr_accessor :punishment_expiry

    # Current rate limit counter (requests in current 1-minute window)
    attr_accessor :rate_limit_count

    # Maximum allowed requests per minute for this endpoint
    attr_accessor :rate_limit_max

    # Remaining requests available in current window (0 if blacklisted)
    attr_accessor :remaining_requests

    # Number of violations in the past 5 minutes
    attr_accessor :violation_count

    # Unix timestamp when violation count resets (0 if no violations)
    attr_accessor :violation_expiry

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'current_level' => :'currentLevel',
        :'endpoint' => :'endpoint',
        :'level_description' => :'levelDescription',
        :'next_level_warning' => :'nextLevelWarning',
        :'punishment_expiry' => :'punishmentExpiry',
        :'rate_limit_count' => :'rateLimitCount',
        :'rate_limit_max' => :'rateLimitMax',
        :'remaining_requests' => :'remainingRequests',
        :'violation_count' => :'violationCount',
        :'violation_expiry' => :'violationExpiry'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'current_level' => :'Integer',
        :'endpoint' => :'String',
        :'level_description' => :'String',
        :'next_level_warning' => :'String',
        :'punishment_expiry' => :'Integer',
        :'rate_limit_count' => :'Integer',
        :'rate_limit_max' => :'Integer',
        :'remaining_requests' => :'Integer',
        :'violation_count' => :'Integer',
        :'violation_expiry' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Unibee::UnibeeApiSystemSubscriptionSubscriptionEndpointBlacklistStatus` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Unibee::UnibeeApiSystemSubscriptionSubscriptionEndpointBlacklistStatus`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'current_level')
        self.current_level = attributes[:'current_level']
      end

      if attributes.key?(:'endpoint')
        self.endpoint = attributes[:'endpoint']
      end

      if attributes.key?(:'level_description')
        self.level_description = attributes[:'level_description']
      end

      if attributes.key?(:'next_level_warning')
        self.next_level_warning = attributes[:'next_level_warning']
      end

      if attributes.key?(:'punishment_expiry')
        self.punishment_expiry = attributes[:'punishment_expiry']
      end

      if attributes.key?(:'rate_limit_count')
        self.rate_limit_count = attributes[:'rate_limit_count']
      end

      if attributes.key?(:'rate_limit_max')
        self.rate_limit_max = attributes[:'rate_limit_max']
      end

      if attributes.key?(:'remaining_requests')
        self.remaining_requests = attributes[:'remaining_requests']
      end

      if attributes.key?(:'violation_count')
        self.violation_count = attributes[:'violation_count']
      end

      if attributes.key?(:'violation_expiry')
        self.violation_expiry = attributes[:'violation_expiry']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          current_level == o.current_level &&
          endpoint == o.endpoint &&
          level_description == o.level_description &&
          next_level_warning == o.next_level_warning &&
          punishment_expiry == o.punishment_expiry &&
          rate_limit_count == o.rate_limit_count &&
          rate_limit_max == o.rate_limit_max &&
          remaining_requests == o.remaining_requests &&
          violation_count == o.violation_count &&
          violation_expiry == o.violation_expiry
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [current_level, endpoint, level_description, next_level_warning, punishment_expiry, rate_limit_count, rate_limit_max, remaining_requests, violation_count, violation_expiry].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Unibee.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
