=begin
#OpenAPI UniBee

#UniBee Api Server

The version of the OpenAPI document: daily,buildtime:202602241319

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'date'
require 'time'

module Unibee
  class UnibeeApiMerchantPlanNewReq
    # Plan Amount
    attr_accessor :amount

    # Plan Currency
    attr_accessor :currency

    # Plan Name
    attr_accessor :plan_name

    # Plan Ids Of Recurring Addon Type
    attr_accessor :addon_ids

    # whether cancel at subscription first trial end，0-false | 1-true, will pass to cancelAtPeriodEnd of subscription
    attr_accessor :cancel_at_trial_end

    # Description
    attr_accessor :description

    # ExternalPlanId
    attr_accessor :external_plan_id

    # who pay the gas for crypto payment, merchant|user
    attr_accessor :gas_payer

    # HomeUrl,Start With: http
    attr_accessor :home_url

    # ImageUrl,Start With: http
    attr_accessor :image_url

    attr_accessor :internal_name

    # Number Of IntervalUnit，em: day|month|year|week
    attr_accessor :interval_count

    # Plan Interval Unit，em: day|month|year|week
    attr_accessor :interval_unit

    # Metadata，Map
    attr_accessor :metadata

    # Plan's MetricLimit List
    attr_accessor :metric_limits

    # Plan's MetricMeteredCharge
    attr_accessor :metric_metered_charge

    # Plan's MetricRecurringCharge
    attr_accessor :metric_recurring_charge

    # Plan's MultiCurrencies
    attr_accessor :multi_currencies

    # Plan Ids Of Onetime Addon Type
    attr_accessor :onetime_addon_ids

    # Default Copy Description
    attr_accessor :product_description

    # Id of product which plan to linked
    attr_accessor :product_id

    # Default Copy PlanName
    attr_accessor :product_name

    # price of trial period， not available for addon
    attr_accessor :trial_amount

    # demand of trial， not available for addon, example, paymentMethod, payment method will ask for subscription trial start
    attr_accessor :trial_demand

    # duration of trial， not available for addon
    attr_accessor :trial_duration_time

    # The type of plan, 1-main plan，2-addon plan, 3-onetime plan, default main plan
    attr_accessor :type

    attr_accessor :us_vat_config

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'amount' => :'amount',
        :'currency' => :'currency',
        :'plan_name' => :'planName',
        :'addon_ids' => :'addonIds',
        :'cancel_at_trial_end' => :'cancelAtTrialEnd',
        :'description' => :'description',
        :'external_plan_id' => :'externalPlanId',
        :'gas_payer' => :'gasPayer',
        :'home_url' => :'homeUrl',
        :'image_url' => :'imageUrl',
        :'internal_name' => :'internalName',
        :'interval_count' => :'intervalCount',
        :'interval_unit' => :'intervalUnit',
        :'metadata' => :'metadata',
        :'metric_limits' => :'metricLimits',
        :'metric_metered_charge' => :'metricMeteredCharge',
        :'metric_recurring_charge' => :'metricRecurringCharge',
        :'multi_currencies' => :'multiCurrencies',
        :'onetime_addon_ids' => :'onetimeAddonIds',
        :'product_description' => :'productDescription',
        :'product_id' => :'productId',
        :'product_name' => :'productName',
        :'trial_amount' => :'trialAmount',
        :'trial_demand' => :'trialDemand',
        :'trial_duration_time' => :'trialDurationTime',
        :'type' => :'type',
        :'us_vat_config' => :'usVATConfig'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'amount' => :'Integer',
        :'currency' => :'String',
        :'plan_name' => :'String',
        :'addon_ids' => :'Array<Integer>',
        :'cancel_at_trial_end' => :'Integer',
        :'description' => :'String',
        :'external_plan_id' => :'String',
        :'gas_payer' => :'String',
        :'home_url' => :'String',
        :'image_url' => :'String',
        :'internal_name' => :'String',
        :'interval_count' => :'Integer',
        :'interval_unit' => :'String',
        :'metadata' => :'Hash<String, Object>',
        :'metric_limits' => :'Array<UnibeeApiBeanPlanMetricLimitParam>',
        :'metric_metered_charge' => :'Array<UnibeeApiBeanPlanMetricMeteredChargeParam>',
        :'metric_recurring_charge' => :'Array<UnibeeApiBeanPlanMetricMeteredChargeParam>',
        :'multi_currencies' => :'Array<UnibeeApiBeanPlanMultiCurrency>',
        :'onetime_addon_ids' => :'Array<Integer>',
        :'product_description' => :'String',
        :'product_id' => :'Integer',
        :'product_name' => :'String',
        :'trial_amount' => :'Integer',
        :'trial_demand' => :'String',
        :'trial_duration_time' => :'Integer',
        :'type' => :'Integer',
        :'us_vat_config' => :'UnibeeApiBeanUSVATConfig'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Unibee::UnibeeApiMerchantPlanNewReq` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Unibee::UnibeeApiMerchantPlanNewReq`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      else
        self.amount = nil
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = nil
      end

      if attributes.key?(:'plan_name')
        self.plan_name = attributes[:'plan_name']
      else
        self.plan_name = nil
      end

      if attributes.key?(:'addon_ids')
        if (value = attributes[:'addon_ids']).is_a?(Array)
          self.addon_ids = value
        end
      end

      if attributes.key?(:'cancel_at_trial_end')
        self.cancel_at_trial_end = attributes[:'cancel_at_trial_end']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'external_plan_id')
        self.external_plan_id = attributes[:'external_plan_id']
      end

      if attributes.key?(:'gas_payer')
        self.gas_payer = attributes[:'gas_payer']
      end

      if attributes.key?(:'home_url')
        self.home_url = attributes[:'home_url']
      end

      if attributes.key?(:'image_url')
        self.image_url = attributes[:'image_url']
      end

      if attributes.key?(:'internal_name')
        self.internal_name = attributes[:'internal_name']
      end

      if attributes.key?(:'interval_count')
        self.interval_count = attributes[:'interval_count']
      end

      if attributes.key?(:'interval_unit')
        self.interval_unit = attributes[:'interval_unit']
      end

      if attributes.key?(:'metadata')
        if (value = attributes[:'metadata']).is_a?(Hash)
          self.metadata = value
        end
      end

      if attributes.key?(:'metric_limits')
        if (value = attributes[:'metric_limits']).is_a?(Array)
          self.metric_limits = value
        end
      end

      if attributes.key?(:'metric_metered_charge')
        if (value = attributes[:'metric_metered_charge']).is_a?(Array)
          self.metric_metered_charge = value
        end
      end

      if attributes.key?(:'metric_recurring_charge')
        if (value = attributes[:'metric_recurring_charge']).is_a?(Array)
          self.metric_recurring_charge = value
        end
      end

      if attributes.key?(:'multi_currencies')
        if (value = attributes[:'multi_currencies']).is_a?(Array)
          self.multi_currencies = value
        end
      end

      if attributes.key?(:'onetime_addon_ids')
        if (value = attributes[:'onetime_addon_ids']).is_a?(Array)
          self.onetime_addon_ids = value
        end
      end

      if attributes.key?(:'product_description')
        self.product_description = attributes[:'product_description']
      end

      if attributes.key?(:'product_id')
        self.product_id = attributes[:'product_id']
      end

      if attributes.key?(:'product_name')
        self.product_name = attributes[:'product_name']
      end

      if attributes.key?(:'trial_amount')
        self.trial_amount = attributes[:'trial_amount']
      end

      if attributes.key?(:'trial_demand')
        self.trial_demand = attributes[:'trial_demand']
      end

      if attributes.key?(:'trial_duration_time')
        self.trial_duration_time = attributes[:'trial_duration_time']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = 1
      end

      if attributes.key?(:'us_vat_config')
        self.us_vat_config = attributes[:'us_vat_config']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @amount.nil?
        invalid_properties.push('invalid value for "amount", amount cannot be nil.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      if @plan_name.nil?
        invalid_properties.push('invalid value for "plan_name", plan_name cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @amount.nil?
      return false if @currency.nil?
      return false if @plan_name.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          amount == o.amount &&
          currency == o.currency &&
          plan_name == o.plan_name &&
          addon_ids == o.addon_ids &&
          cancel_at_trial_end == o.cancel_at_trial_end &&
          description == o.description &&
          external_plan_id == o.external_plan_id &&
          gas_payer == o.gas_payer &&
          home_url == o.home_url &&
          image_url == o.image_url &&
          internal_name == o.internal_name &&
          interval_count == o.interval_count &&
          interval_unit == o.interval_unit &&
          metadata == o.metadata &&
          metric_limits == o.metric_limits &&
          metric_metered_charge == o.metric_metered_charge &&
          metric_recurring_charge == o.metric_recurring_charge &&
          multi_currencies == o.multi_currencies &&
          onetime_addon_ids == o.onetime_addon_ids &&
          product_description == o.product_description &&
          product_id == o.product_id &&
          product_name == o.product_name &&
          trial_amount == o.trial_amount &&
          trial_demand == o.trial_demand &&
          trial_duration_time == o.trial_duration_time &&
          type == o.type &&
          us_vat_config == o.us_vat_config
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [amount, currency, plan_name, addon_ids, cancel_at_trial_end, description, external_plan_id, gas_payer, home_url, image_url, internal_name, interval_count, interval_unit, metadata, metric_limits, metric_metered_charge, metric_recurring_charge, multi_currencies, onetime_addon_ids, product_description, product_id, product_name, trial_amount, trial_demand, trial_duration_time, type, us_vat_config].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Unibee.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
