=begin
#OpenAPI UniBee

#UniBee Api Server

The version of the OpenAPI document: daily,buildtime:202602241319

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'cgi'

module Unibee
  class IntegrationsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Disconnection Quickbooks
    # @param [Hash] opts the optional parameters
    # @return [MerchantAuthSsoClearTotpPost200Response]
    def merchant_integration_quickbooks_disconnection_get(opts = {})
      data, _status_code, _headers = merchant_integration_quickbooks_disconnection_get_with_http_info(opts)
      data
    end

    # Disconnection Quickbooks
    # @param [Hash] opts the optional parameters
    # @return [Array<(MerchantAuthSsoClearTotpPost200Response, Integer, Hash)>] MerchantAuthSsoClearTotpPost200Response data, response status code and response headers
    def merchant_integration_quickbooks_disconnection_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: IntegrationsApi.merchant_integration_quickbooks_disconnection_get ...'
      end
      # resource path
      local_var_path = '/merchant/integration/quickbooks/disconnection'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'MerchantAuthSsoClearTotpPost200Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"IntegrationsApi.merchant_integration_quickbooks_disconnection_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: IntegrationsApi#merchant_integration_quickbooks_disconnection_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get Quickbooks Authorization Connection URL
    # @param [Hash] opts the optional parameters
    # @option opts [String] :return_url ReturnUrl
    # @return [MerchantIntegrationQuickbooksGetAuthorizationUrlGet200Response]
    def merchant_integration_quickbooks_get_authorization_url_get(opts = {})
      data, _status_code, _headers = merchant_integration_quickbooks_get_authorization_url_get_with_http_info(opts)
      data
    end

    # Get Quickbooks Authorization Connection URL
    # @param [Hash] opts the optional parameters
    # @option opts [String] :return_url ReturnUrl
    # @return [Array<(MerchantIntegrationQuickbooksGetAuthorizationUrlGet200Response, Integer, Hash)>] MerchantIntegrationQuickbooksGetAuthorizationUrlGet200Response data, response status code and response headers
    def merchant_integration_quickbooks_get_authorization_url_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: IntegrationsApi.merchant_integration_quickbooks_get_authorization_url_get ...'
      end
      # resource path
      local_var_path = '/merchant/integration/quickbooks/get_authorization_url'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'returnUrl'] = opts[:'return_url'] if !opts[:'return_url'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'MerchantIntegrationQuickbooksGetAuthorizationUrlGet200Response'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"IntegrationsApi.merchant_integration_quickbooks_get_authorization_url_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: IntegrationsApi#merchant_integration_quickbooks_get_authorization_url_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
